# Generated by Django 4.2.30 on 2026-04-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50)),
                ('source', models.CharField(default='slack_mock', max_length=50)),
                ('generated_title', models.CharField(max_length=255)),
                ('generated_content', models.TextField()),
                ('confluence_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published'), ('discarded', 'Discarded')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('vp_ops', 'VP of Operations'), ('developer', 'Developer')], max_length=20)),
                ('display_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VPMetricsMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_saved', models.IntegerField(default=342)),
                ('dollars_saved', models.IntegerField(default=25650)),
                ('kb_capture_rate', models.FloatField(default=88.0)),
                ('mttr_trend_data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'VP Metrics (Mock)',
            },
        ),
    ]
